# Generated by Django 4.0.2 on 2022-02-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(blank=True, null=True, upload_to='imports/%m/%Y/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'arquivo',
                'verbose_name_plural': 'arquivos',
            },
        ),
    ]
